name: java-spring-aws-sqs-plugin
description: Plugin to enable Spring Cloud AWS SQS in Spring Boot Java applications
display-name: java-spring-aws-sqs-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app


hooks:
  ##
  # Parses pom.xml and create some "computed" inputs
  ##
  - type: run-script
    trigger: before-input
    script: scripts/open-pom.py

  ##
  # Edit pom.xml
  ##
  - type: edit
    path: pom.xml
    trigger: after-render    
    changes:
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom.xml
          when:
            not-exists-snippet: snippets/snippet-pom.xml
      - search:
          string: "</dependencies>"
          insert-after:
            snippet: snippets/snippet-pom-dependencyManagement.xml
          when:
            not-exists-snippet: snippets/snippet-pom-dependencyManagement.xml

  ##
  # Edit application.yaml
  ##
  - type: edit
    path: src/main/resources/application.yaml
    trigger: after-render    
    changes:
      - insert:
          line: -1
          snippet: snippets/snippet-application.yaml
          when:
            not-exists-snippet: snippets/snippet-application.yaml

  ##
  # Edit application-test.yaml
  ##
  - type: edit
    path: src/test/resources/application-test.yaml
    trigger: after-render 
    changes:
      - insert:
          line: -1
          snippet: snippets/snippet-application-test.yaml
          when:
            not-exists-snippet: snippets/snippet-application-test.yaml   
  
  ##
  # Create or edit docker-compose.yaml
  ##
  - type: render-templates
    trigger: after-render
    path: snippets/docker-localstack
